language: php
sudo: false
notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - develop

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer require "phpunit/phpunit=^6.0.0"
      composer require "10up/wp_mock=0.3.*@dev"
    elif [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
          composer require "phpunit/phpunit=5.6.*"
          composer require "10up/wp_mock" "*"
    else
      composer require "phpunit/phpunit=4.*"
      composer require "10up/wp_mock" "*"
    fi
    composer require "phpunit/phpcov"
    composer require "codeclimate/php-test-reporter"
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover clover.xml
after_success:
  - ./vendor/bin/test-reporter --coverage-report=clover.xml
